POST http://localhost:8084/new/wallet
Content-Type: application/json

{
  "usuarioID": "3",
  "telefono": "0321",
  "email": "mario@gmail.com"
}

###

POST http://localhost:8084/new/transaction/
Content-Type: application/json

{
  "walletOrigen": "2",
  "walletDestino": "3",
  "valor": 17.0,
  "motivo": "Pago de servicios"
}