POST http://localhost:8084/new/wallet
Content-Type: application/json

{
  "usuarioID": "2",
  "telefono": "120391230",
  "email": "daniel@gmail.com"
}

###

POST http://localhost:8084/new/transaction/
Content-Type: application/json

{
  "walletOrigen": "2",
  "walletDestino": "3",
  "valor": 17.0,
  "motivo": "Pago de servicios"
}